version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: 
      - bash
      - -c
      - |
        python manage.py makemigrations user news
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      default_bridge:
        ipv4_address: 192.168.80.2
    depends_on:
      - rabbitmq
      - pgdb
  celery:
    build: .
    container_name: celery-worker
    command: celery -b rabbitmq -A config worker -l info
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - CELERY_BROKER_URL='amqp://localhost'
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/usr/src/app/
    networks:
      default_bridge:
        ipv4_address: 192.168.80.3
    depends_on:
      - django
      - rabbitmq
  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -b rabbitmq -A config beat -l info
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - CELERY_BROKER_URL='amqp://localhost'
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/usr/src/app/
    networks:
      default_bridge:
        ipv4_address: 192.168.80.4
    depends_on:
      - celery
      - django
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      default_bridge:
        ipv4_address: 192.168.80.5
  pgdb:
    image: postgres
    container_name: "pgdb"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      default_bridge:
        ipv4_address: 192.168.80.6

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/20